"""empty message

Revision ID: dfb78b2e8cf4
Revises: d62ddcb767af
Create Date: 2020-11-12 18:12:12.791418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb78b2e8cf4'
down_revision = 'd62ddcb767af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'id')
    op.add_column('users', sa.Column('shore_order', sa.ARRAY(sa.Integer(), dimensions=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shore_order')
    op.add_column('favorites', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
