# Generated by Django 2.2.10 on 2020-11-05 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surf_spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surf_spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surf_spots.SurfSpots')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_spots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
