# Generated by Django 2.2.10 on 2020-11-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_spots', '0002_favoritespots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritespots',
            old_name='surf_spot_id',
            new_name='surf_spot',
        ),
        migrations.RenameField(
            model_name='favoritespots',
            old_name='user_id',
            new_name='user',
        ),
    ]
