# Generated by Django 2.2.10 on 2020-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_spots', '0003_auto_20201105_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspots',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='surfspots',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
